### ISSUE TITLE
Error on Web File Import (v9)

### ISSUE THREAD

**Issue by readyxrm** [MscrmTools/MscrmTools.PortalRecordsMover#11]
I am trying to move a "Custom" portal on Dynamics 365 v9.  I am getting the follow errors on all the webfile records in the log:

**2018-09-04 07:55:23.193 PM		Error	homehero.jpg (Web File/2aa45984-44e2-e511-9405-000d3a3107a2): 'adx_webfile' entity doesn't contain attribute with Name = 'adx_ideaid' and NameMapping = 'Logical'.**

It appears to be looking for a link to the ideas portal, but I don't have that portal solution installed.  This is working on Dynamics 365 8.2 (or was a few days ago).  Just wondering if Microsoft did an update to portals that broke the portal data mover?

Thanks,
Nick

**Comment by readyxrm** [comment]
I seem to be missing one of the base portal solutions on my destination instance, that might be the problem.

**Comment by MscrmTools** [comment]
was it the problem? I close the issue, just tell me if we need to reopen it

**Comment by readyxrm** [comment]
Yes, for some reason not all the base Portal solutions were installed.  Once they were, everything worked fine.  Consider issue closed and "user error" :)
