### ISSUE TITLE
Type 'Annotation' with data contract name 'Annotation:http://schemas.datacontract.org/2004/07/' is not expected

### ISSUE THREAD

**Issue by TiagoMCardoso** [MscrmTools/MscrmTools.PortalRecordsMover#15]
I'm selecting all entities from the left menu and retrieving all the records, then I select a Web Site and click on "Export Records" when the following error happens:

"Type 'Annotation' with data contract name 'Annotation:http://schemas.datacontract.org/2004/07/' is not expected. Consider using a DataContractResolver if you are using DataContractSerializer or add any types not known statically to the list of known types - for example, by using the KnownTypeAttribute attribute or by adding them to the list of known types passed to the serializer."

![image](https://user-images.githubusercontent.com/34498544/57596994-c0afd500-7590-11e9-8f65-715e32967158.png)

If I open the XML file, there is only that:

`<?xml version="1.0" encoding="utf-8"?>
<EntityCollection xmlns:i="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schemas.microsoft.com/xrm/2011/Contracts">
  <Entities>
    <Entity xmlns:d3p1="http://schemas.datacontract.org/2004/07/" i:type="d3p1:Annotation" />
  </Entities>
</EntityCollection>`

If I select the Web Site before hit "Retrieve Records", I got this error: 

![image](https://user-images.githubusercontent.com/34498544/57597260-0a4cef80-7592-11e9-9af6-b3e7ca704bf1.png)

If I don't select Invitations, I got same error in Forum and Page Notifications

**Comment by MscrmTools** [comment]
Can you tell me what is your version of portal?

**Comment by TiagoMCardoso** [comment]
9.0.12.10

**Comment by MscrmTools** [comment]
is it still happening?

**Comment by roxannaappleby** [comment]
Yes, it is still for me. Any solution to this please? Thanks.

**Comment by MscrmTools** [comment]
All the tests I’m performing includes annotations and I don’t get any issue...
Did you try the latest version released yesterday?

**Comment by MscrmTools** [comment]
I asked my MVP colleagues and this error seems to be due to the presence of a plugin/tool in XrmToolBox that uses an early bound definition for entity Annotation.
To confirm this, you could try to have an XrmToolBox installation with only Portal Records Mover and try again to work with web files

**Comment by MscrmTools** [comment]
Next version (release in few minutes) will inform you of the faulting tool. You should be able to remove it
