### ISSUE TITLE
Unhandled exception while importing the file in portal record mover

### ISSUE THREAD

**Issue by thiashton** [MscrmTools/MscrmTools.PortalRecordsMover#16]
Below issue while importing records in portal record mover.
Please find the attached file for more info.
[XRM Issue.txt](https://github.com/MscrmTools/MscrmTools.PortalRecordsMover/files/3338161/XRM.Issue.txt)
[XRM Issue.txt](https://github.com/MscrmTools/MscrmTools.PortalRecordsMover/files/3338164/XRM.Issue.txt)

System.NullReferenceException: Object reference not set to an instance of an object.
   at MscrmTools.PortalRecordsMover.MyPluginControl.<>c.<Import>b__34_5(Entity e)

**Comment by thiashton** [comment]
Additional Info : Issue is with only "**web file**" import.

**Comment by MscrmTools** [comment]
Can you test with this version, please?

[MscrmTools.PortalRecordsMover.zip](https://github.com/MscrmTools/MscrmTools.PortalRecordsMover/files/3354911/MscrmTools.PortalRecordsMover.zip)

**Comment by thiashton** [comment]
Can you please explain in detail what needs to be done with the dll after loading Portal Record Mover on the XRMToolBox?

**Comment by MscrmTools** [comment]
Sorry, you need to replace the existing assembly with the one I sent BEFORE opening XrmToolBox.
XrmToolBox will then use this new version.
If you don't know where are the assembly, open XrmToolBox, click on Tools\Settings, then go on tab "Paths", click on storage path then navigate in "Plugins" folder. Paste the new file there

**Comment by thiashton** [comment]
Thank you..! 
That worked. Can I know what was the issue? It showed a message like Removing JS restriction.

**Comment by MscrmTools** [comment]
the real error was that some of the annotation in your web files don't have a filename attribute set. I thought it was always filled. it seems not

**Comment by MscrmTools** [comment]
I will push a new version with the fix soon

**Comment by thiashton** [comment]
Great, thanks!
