### ISSUE TITLE
Unable get backup of the Portal

### ISSUE THREAD

**Issue by vinaypugaliagithub** [MscrmTools/MscrmTools.PortalRecordsMover#18]
Hi,

I try to take backup of the Portal using this tool but I get the attached error.

![Portal_Backup_error](https://user-images.githubusercontent.com/11075921/65249507-bb036680-db11-11e9-8037-9b8381e0552d.png)

Could you advise what needs to be done to get rid of this?

**Comment by MscrmTools** [comment]
You missed two years of XrmToolBox updates!
Please update your XrmToolBox and you should be good

**Comment by vinaypugaliagithub** [comment]
Thank you for the quick reply. When we try to that I get the attached message,

![XRM_Toolbox_update](https://user-images.githubusercontent.com/11075921/65252730-197f1380-db17-11e9-885c-2f702b23599d.png)

**Comment by MscrmTools** [comment]
I know but you got stuck with a version that cannot update itself... 
can you download the latest version from www.xrmtoolbox.com?
