### ISSUE TITLE
Error when attempting to load items

### ISSUE THREAD

**Issue by CesarBTC** [MscrmTools/MscrmTools.PortalRecordsMover#2]
I am using the Portal Records Mover plugin v1.2017.7.3 on XRMToolBox v1.2017.6.16.
I am connected to Dynamics CRM 365. I can issue FetchXML queries that return data so I verified that I am connected. I am connected using an administrator account.

When I open the Portal Records Mover and click on Load Items, The Loading entities... dialog pops up and spins for 30 seconds or so, then I catch a flash of a Loading websites dialog before the following error pops up:

An error occurred: The entity with a name = 'adx_website' was not found in the MetadataCache.

Please advise.

**Comment by MscrmTools** [comment]
Are you sure Portal solutions are installed on your organization?

**Comment by CesarBTC** [comment]
I believe that you are correct. In spite of the fact that they indicated otherwise, my client does not actually have Portal solutions installed on their organization. 

The error makes sense. Please close the issue.
