### ISSUE TITLE
Possibility to compare differences between target website and exported xml file?

### ISSUE THREAD

**Issue by teppolainio** [MscrmTools/MscrmTools.PortalRecordsMover#20]
Has there been any thoughts about adding possibility for comparing content on target site and content read from local disk? This would make it possible to catch differences on customers current production environment if one could select previously imported production website xml file from version control and compare it to the current website content present on the target environment.

**Comment by MscrmTools** [comment]
Not sure it will be the tool for such a feature but the idea is interesting anyway

**Comment by MscrmTools** [comment]
Another XrmToolBox tool does that : https://www.xrmtoolbox.com/plugins/CVN.XrmToolBox.RecordCompare/
