### ISSUE TITLE
Possibility to export single file per record to improve interaction with version control

### ISSUE THREAD

**Issue by teppolainio** [MscrmTools/MscrmTools.PortalRecordsMover#21]
Has there been any thoughts about adding possibility to serialize EntityCollection during export to single file per Entity instance instead of creating a massive file from EntityCollection instance? I'm asking this because it would help us on improving our ALM process if there would be structure like:
* &lt;Root folder&gt;
  * adx_something
    * &lt;guid 1&gt;.xml
    * &lt;guid 2&gt;.xml
  * adx_anything
    * &lt;guid 1&gt;.xml
    * &lt;guid 2&gt;.xml

This basically would change behaviour towards the way [SolutionPackager](https://docs.microsoft.com/en-us/dynamics365/customer-engagement/developer/use-source-control-solution-files) tool works. Of course this would require similar features for import.

**Comment by MscrmTools** [comment]
Export part is done! Still need to work on the import side

**Comment by teppolainio** [comment]
That's great news. I didn't expect you to start implementations right away though!

**Comment by MscrmTools** [comment]
a great idea needs an immediate implementation :D
