### ISSUE TITLE
Duplicate css files

### ISSUE THREAD

**Issue by peterf11** [MscrmTools/MscrmTools.PortalRecordsMover#22]
When a web file (css) is  moved from one environment to another and the the css file has been updated the target record ends up with 2 web files (original and new)

**Comment by MscrmTools** [comment]
Can you be more precise on what is the update operation you are talking about? Portal records mover maintain the GUID of records so I don’t understand how is this possible

**Comment by peterf11** [comment]
UNCLASSIFIED
If I update a CSS web file record in DEV (by deleting the note and adding a new one) and then copy that record to TEST I end up with a web file record with 2 notes.

Note: I am only doing it this way because the Portal Code Editor currently has a problem with editin CSS web files.

**Comment by MscrmTools** [comment]
Ok, that makes perfect sense! Portal Records Mover should handle the fact to keep only one annotation per web file, the one coming from source.

And for information, I just released a new version of Portal Code Editor that fixes the CSS issue
