### ISSUE TITLE
Unable to save settings

### ISSUE THREAD

**Issue by jamesnovak** [MscrmTools/MscrmTools.PortalRecordsMover#23]
'MscrmTools.PortalRecordsMover.AppCode.ExportSettings' because it contains property 'ZipFolderStructure' which has no public setter.

(same issue on loading existing settings)

call stack/exception 

> ************** Exception Text **************
> System.Exception: Error while serializing: Cannot deserialize type 'MscrmTools.PortalRecordsMover.AppCode.ExportSettings' because it contains property 'ZipFolderStructure' which has no public setter.
>    at McTools.Xrm.Connection.XmlSerializerHelper.SerializeToFile(Object o, String path)
>    at MscrmTools.PortalRecordsMover.MyPluginControl.saveSettingsToolStripMenuItem_Click(Object sender, EventArgs e)
>    at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
>    at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
>    at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
>    at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
>    at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
>    at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
>    at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
>    at System.Windows.Forms.Control.WndProc(Message& m)
>    at System.Windows.Forms.ToolStrip.WndProc(Message& m)
>    at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
>    at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>

**Comment by MscrmTools** [comment]
Sorry for that. Fix on its way!
