### ISSUE TITLE
Unable to select Website 

### ISSUE THREAD

**Issue by matiasroque** [MscrmTools/MscrmTools.PortalRecordsMover#25]
I connect to my organization where i have configured the portal. When i select "Get records from website", the picklist is shown empty and i'm not able to select the website and move forward. 

The website is active in the CRM instance.

Am I skipping any step?

**Comment by matiasroque** [comment]
![portal records mover issue](https://user-images.githubusercontent.com/57361194/68132138-f066e680-fefc-11e9-82b4-0eacbdc8f2c9.png)

**Comment by MscrmTools** [comment]
You should load entities first

**Comment by matiasroque** [comment]
I tried to do that, but when I click "Load Items" I get this message:

![image](https://user-images.githubusercontent.com/57361194/68142625-9707b300-ff0e-11e9-89d1-70bde5b6bc18.png)

**Comment by MscrmTools** [comment]
It seems you are out to date with your version of XrmToolBox.
Please upgrade to latest version

**Comment by matiasroque** [comment]
Is the 1.2019.7.34?

**Comment by matiasroque** [comment]
Yeah it was that one, it works now! Thank you very much!

**Comment by MscrmTools** [comment]
You’re very welcome!
