### ISSUE TITLE
Error when importing records

### ISSUE THREAD

**Issue by matiasroque** [MscrmTools/MscrmTools.PortalRecordsMover#26]
Hi, 

I'm trying to import portal records form a dev instance to another one, but when i connect to the destination organization I get the following message:

![image](https://user-images.githubusercontent.com/57361194/68213549-8e6cb680-ffba-11e9-8727-a7d86b1437a1.png)

When I firstly connect to the source organization and select the entities, I cannot find the Note entity to deselect it, because I don't need it. 

How can I solve this?

Thanks in advance.

**Comment by MscrmTools** [comment]
Notes are retrieved if you try to transfer Web File entity.

**Comment by matiasroque** [comment]
Yes, I deselected Web File entity and could export the other records. The problem is that I added some web pages at the source organization and wanted to export them, but I can create manually, no problem. For the future, is there a way to avoid that issue?

**Comment by MscrmTools** [comment]
I’m checking with Microsoft

**Comment by matiasroque** [comment]
Ok, thanks!

**Comment by MscrmTools** [comment]
Ok, so the issue might be related to another plugin that is interacting badly with Portal Records Mover.
Could you try to remove all plugins except Portal Records Mover from your Plugins folder, then try again to move Web Files records?

**Comment by MscrmTools** [comment]
Next version (release in few minutes) will inform you of the faulting tool. You should be able to remove it
