### ISSUE TITLE
When exporting web access control rules it doesnt export the associated webrole along with it

### ISSUE THREAD

**Issue by sindhuja29** [MscrmTools/MscrmTools.PortalRecordsMover#28]

**Comment by sindhuja29** [comment]
When i exported xml which included webpage access control rule, the associated web role is not getting exported into the xml.Is there a way to include it in the xml?

**Comment by MscrmTools** [comment]
Did you select webrole entity to export too? The tool does not automatically export associated entities.

**Comment by MscrmTools** [comment]
Ok, the records were exported but not imported.
Fix on its way

**Comment by sindhuja29** [comment]
> Ok, the records were exported but not imported.
> Fix on its way

Yes thats right
