### ISSUE TITLE
Odering of exported XML keys differs

### ISSUE THREAD

**Issue by andreasziegl** [MscrmTools/MscrmTools.PortalRecordsMover#30]
Hi,
first thank you for the amazing tool! The PortalRecordsMover is really very helpful. Also the new feature to export the records in seperate files is very helpful. 
But there is a small issue which makes it hard to properly track changes via GIT:
The  ordering of the XML keys is not consistent when I export the portal from different environments. This makes comparing of files quite difficult.
Please find an example diff attached and the switched keys with lines below. 

1.: timezoneruleversionnumber:
First environment: Line 25
Second environment: Line 9
2.: owneridtype:
First environment: Line 33
Second environment: Line 29
3.: modifiedon:
First environment: Line 74
Second environment: Line 66

Maybe you have the possibility to adapt the XML export. I tried to find a solution by myself but have to admit, that I'm not very experienced there.

Best regards
Andreas

[diff report.zip](https://github.com/MscrmTools/MscrmTools.PortalRecordsMover/files/4034504/diff.report.zip)

**Comment by MscrmTools** [comment]
Hi, thanks for reporting. 

I will try to see if I can implement some kind of XML nodes ordering

**Comment by MscrmTools** [comment]
New release to be shipped soon
