### ISSUE TITLE
Entity Permissions-Web Role association and Access Control Rule-Web Role association not migrating

### ISSUE THREAD

**Issue by vnathglo** [MscrmTools/MscrmTools.PortalRecordsMover#31]
Hello, I'm looking to move from dev to tst environment the following dynamics portal configurations
- Entity Permissions
- Web Roles
- Entity Permissions associated with the Web role
- Web Access Control Rules
- Web Access Control Rules associated with the web role

The entity permissions, web role, and web access control rules' basic definitions are moving thru the portal records mover. But the entity permission-webrole association is not migrating, nor is the wacr-webrole association (even though I had selected which associations to move). The log is showing error like below:

2020-02-04 07:18:35.709 PM		Error	(N/A) (Entity Permission / Web Role/87cf0706-b547-ea11-a9af-001dd8308025): The 'Update' method does not support entities of type 'adx_entitypermission_webrole'.

The version of Portal Records Mover that's doing this is: 1.2020.1.18

Thanks

**Comment by MscrmTools** [comment]
I just tried with the latest version to migrate Web Role / Entity Permission and it did work as expected. 
The code is checking the data inside entity and if it finds three guids, that means it's a NN relationship.
I don't see how it could fail. Are you sure you don't have a plugin that tries to perform some action during association?
