### ISSUE TITLE
Load Items issue

### ISSUE THREAD

**Issue by OOlashyn** [MscrmTools/MscrmTools.PortalRecordsMover#33]
Hi @MscrmTools ,
I have problem - when I press Load items button it shows loading message and never ends. We tried to connect from different machines and with different users however issue still occurs. We are using the latest version of the tool.

**Comment by MscrmTools** [comment]
Don’t know if it changes anything but is a powerapps portal or a Dynamics portal?

**Comment by OOlashyn** [comment]
It is a Dynamics Portal. Everything worked fine on Friday. We didn't have any updates in the system since then.

**Comment by MscrmTools** [comment]
I will check with one of my portals

**Comment by MscrmTools** [comment]
Just checked on two of the portals I have access to and everything worked as expected

**Comment by OOlashyn** [comment]
Hi @MscrmTools,
For some reasons everything works fine right now. I will close this issue. Thanks for help.
