### ISSUE TITLE
Automated Deployment?

### ISSUE THREAD

**Issue by seanmcne** [MscrmTools/MscrmTools.PortalRecordsMover#34]
Do you have an Azure Dev Ops task or powershell module that can be used for automated deployments using this record format?

**Comment by MscrmTools** [comment]
Actually yes. Jim Novak uses this repo to create command line, not really an Azure DevOps task but can help

**Comment by frick-brian** [comment]
You could use the configuration migration CICD tasks to do the same.

**Comment by MscrmTools** [comment]
Here is the command line I was talking about : https://github.com/jamesnovak/PortalRecordsMoverConsole
