### ISSUE TITLE
Facing Error: Index was outside the bounds of array

### ISSUE THREAD

**Issue by aluzaja178** [MscrmTools/MscrmTools.PortalRecordsMover#35]
Hi, 

I am trying to move portal records from one environment to another and getting error on records mover. Please see attachment.

![Error](https://user-images.githubusercontent.com/22441517/81103727-e5802380-8f2a-11ea-9478-a88beae5b1fa.PNG)

**Comment by MscrmTools** [comment]
can you tell me what steps you are doing to get the error ?

**Comment by aluzaja178** [comment]
Its fixed. I was putting some unwanted entities during export. Just unchecked those entities, and its fixed. Thanks

**Comment by MscrmTools** [comment]
I'm still curious about what were the faulty entities? just to check the code
