### ISSUE TITLE
Web Files not pushing Notes when using Transfer option

### ISSUE THREAD

**Issue by oliverfrodrigues** [MscrmTools/MscrmTools.PortalRecordsMover#37]
I noticed an issue that when using the **Transfer** option for Web Files, the notes aren't transferred
When using export/import it works fine
I am using community portals on-prem with D365 on-prem, haven't tried with Online

**Comment by MscrmTools** [comment]
Thank you for reporting. I will review this issue ASAP

**Comment by MscrmTools** [comment]
@oliverfrodrigues I just tested to transfer web files and the associated notes were correctly transferred.

**Comment by oliverfrodrigues** [comment]
thanks for letting me know, might be something odd with my environment, will try again another time 
thanks
