### ISSUE TITLE
Beginner. Import fail line 1. Same schema. Expecting 'Entity' encounters 'EntityCollection'

### ISSUE THREAD

**Issue by tacklers** [MscrmTools/MscrmTools.PortalRecordsMover#38]
Very happy to have found this tool and hope I can get it working to copy CDS Non-Dynamics portal.
Exported Custom portal okay from Tenant. A. orgcdcf6511.crm4
Blank portal created on Tenant. B org14440551.crm11
Import fails with below error. Seems a very close naming thing. Where should I start looking. 
Not a coder but tend to find things out!
Many thanks, Richard

ERROR
************** Exception Text **************
System.Runtime.Serialization.SerializationException: Error in line 1 position 127. Expecting element 'Entity' from namespace 'http://schemas.microsoft.com/xrm/2011/Contracts'.. Encountered 'Element'  with name 'EntityCollection', namespace 'http://schemas.microsoft.com/xrm/2011/Contracts'.

Import file
[MSCRM-tackroom-export.zip](https://github.com/MscrmTools/MscrmTools.PortalRecordsMover/files/4942426/MSCRM-tackroom-export.zip)

Error log
[records-mover-schema-mismatch-error.zip](https://github.com/MscrmTools/MscrmTools.PortalRecordsMover/files/4942437/records-mover-schema-mismatch-error.zip)

---
- Deployment: Online
- DB Version: 9.1.0.19852
- Connection Controls Version: 1.2020.5.33
- XrmToolBox Version: 1.2020.6.40
- Tool Version: 1.2020.6.20

**Comment by MscrmTools** [comment]
Hi @tacklers, not sure why you are getting this error message but could you try to export data using options below

![image](https://user-images.githubusercontent.com/10774317/87915988-23dda700-ca73-11ea-8276-16dbaf22d3a0.png)

Then import by choosing zip file as import source

**Comment by tacklers** [comment]
Great steer. Excellent. It works for me. Thank you
I could export a portal, either reset or not,  from one tenant to another.
Had a couple of glitches with adx_inviteredemptions and web files but easy to narrow down by just exporting those singly to help wade through audit logs to find import errors. 
You may have a counting glitch, see attached as the GUI display stops after web files. Probably because it retrieved 58 records,  I deselected the error one so export/import was 57. 
Keep up the invaluable work!
Cheers, Richard   

[import-completed-okay](https://user-images.githubusercontent.com/19391937/87948561-c78f7d00-ca9c-11ea-978a-12f8309034ec.png)

**Comment by tacklers** [comment]
Hold up!
I stand corrected on the GUI record count and attach second page showing that counts do resume.

 
![import-completed-okay-second-page](https://user-images.githubusercontent.com/19391937/87950328-12aa8f80-ca9f-11ea-9525-1bc5321b5a75.png)

**Comment by MscrmTools** [comment]
Sorry, my bad English... I'm not sure to understand. 
Is there still anything not working as expected?

**Comment by tacklers** [comment]
The migrated portal works okay but I still need to setup contacts, permissions and entities. So I cannot confirm 100%.
I was puzzled that some entities, say site settings with 45 entries do not show under the second phase 'success' column.
Maybe because they have no relationships or lookups to build?

**Comment by MscrmTools** [comment]
Yes, you did understand correctly. Second phase is only used when lookups need to be populated
