### ISSUE TITLE
404 error on trying to export records

### ISSUE THREAD

**Issue by davegoopot** [MscrmTools/MscrmTools.PortalRecordsMover#39]
I'm using the Records Mover version 1.2020.6.20. I'm encountering the following problem. Any advice greatly appreciated.

1. Open the Portal Records Mover and connect to my D365 Online instance
2. Click Load Items
3. Once all items loaded click "Select all"
4. Click "Retrieve records"
5. Once all have loaded, selecting no other filters/options, click "Export records"

Result = Error box pops up with "An error occurred: Error occurred. Message: 'The remote server returned an error: (404) Not Found"

**Comment by davegoopot** [comment]
I have a similar error using the MS DataMigrationUtility. This reports "Failed Schema Vaildation, Missing Entities: adx_contentaccesslevel , adx_contentaccesslevel , adx_communityforum , adx_communityforumaccesspermission , adx_communityforumannouncement , adx_forumthreadtype"

**Comment by davegoopot** [comment]
Found the problem. It was an issue with a custom Annotation plugin on our D365 instance. 

I found the issue by using the MS Data Migration Utility as I could find the log files. Are there equivalent detailed log files for the Records Mover?

**Comment by MscrmTools** [comment]
There is no log file for records export, no.
