### ISSUE TITLE
Export all records (not just the Portal ones)

### ISSUE THREAD

**Issue by blandine** [MscrmTools/MscrmTools.PortalRecordsMover#40]
Hi,
Thanks for this great tool 👍 

I'd like to export all my CDS records to import them in another environment (dev VS prod).
I noticed the PortalRecordsMover tool exports only the records linked to the portal (but not the custom entities for example).
Is there a way to do  it? I'm open to fork and do another plugin for this use case, but I need some direction since I'm quite a newbie on this platform.

Thanks

**Comment by MscrmTools** [comment]
There already is a tool for that. You can use Configuration Migration from CDS SDK that allows you to export/import data across environments. Unless it does not fit your needs for some reason?

**Comment by blandine** [comment]
Thanks ! It does fit indeed :) It seems that I was just unable to find this tool
