### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by rickjan130** [MscrmTools/MscrmTools.PortalRecordsMover#41]
I'm getting an ArgumentNullException: Value cannot be null exception immediately after the Remove file restriction functionality. I have included the log file and a screen shot.  I am a first time user so it's probably something in the exported data but I'm unsure how to troubleshoot the issue.  I did remove the web files from the export but that made no difference.  I'm using version 1.2020.9.21
[MscrmTools.PortalRecordsMover.log](https://github.com/MscrmTools/MscrmTools.PortalRecordsMover/files/5308062/MscrmTools.PortalRecordsMover.log)
![Import error](https://user-images.githubusercontent.com/18168141/94735493-17ee4b00-0328-11eb-8eff-5ee962c48e39.png)

**Comment by MscrmTools** [comment]
No. Issue should be on my side I guess, as it occurs when removing file restriction...
I just need to find time to test and fix this

**Comment by MscrmTools** [comment]
@rickjan130 sorry for the delay... There should be more info in a log file. Would you have it (if you can reproduce)?

**Comment by MscrmTools** [comment]
@rickjan130 Can you tell me if the issue still occurs?
