### ISSUE TITLE
CSS files not showing as modified

### ISSUE THREAD

**Issue by OOlashyn** [MscrmTools/MscrmTools.PortalRecordsMover#44]
Hi All,

Today when transferring Web Files I noticed that list wasn't containing any modified css files.

Steps to recreate issue:

1. Modify css file.
2. In record mover select Web File and check Get records modified on or after and select today's date.
3. Hit Retrieve records.

Expected result;

Css file is listed in Web File list.

Actual result:

Web File list is empty.

**Comment by MscrmTools** [comment]
Thanks for reporting

I do have a specific processing for webfiles/notes but I found a bug so I will fix this as soon as possible
