### ISSUE TITLE
Import Error 

### ISSUE THREAD

**Issue by SeanExum** [MscrmTools/MscrmTools.PortalRecordsMover#45]
Hello,

It appears the new version throws the following error on import of a portal that includes web pages.  See screen shot and error log provided.

Thanks

![image](https://user-images.githubusercontent.com/77765044/105354898-39b55b80-5bbf-11eb-85c5-e0898e31fec2.png)

[MscrmTools.PortalRecordsMoverErrorLog.log](https://github.com/MscrmTools/MscrmTools.PortalRecordsMover/files/5849443/MscrmTools.PortalRecordsMoverErrorLog.log)

**Comment by MscrmTools** [comment]
The error code 0x80040265 in the log indicates that a custom code (likely a plugin) is throwing this exception. It seems a custom code is triggered when creating or deleting a note (I'm testing this to ensure javascript restriction is removed correctly).
So the error is not on Portal Records Mover
