### ISSUE TITLE
Display Language Code on Views

### ISSUE THREAD

**Issue by readyxrm** [MscrmTools/MscrmTools.PortalRecordsMover#46]
Hey Tanguy!

This tool has been working great. 

I have a feature request that I hope isn't too big of an ask, is there a way that we could show the website language lookup on the assets that are language specific?  (web pages, content snippets, weblinks).  In some cases, I only want to move assets of only a specific language over.

(Filtering by language when retrieving will be also awesome)

Attached is a screenshot of what I mean.

![portalmover](https://user-images.githubusercontent.com/18264651/105549361-d9adda80-5cce-11eb-991b-63cf33ab3de8.png)

Cheers
Nick

---
- Deployment: Online
- DB Version: 9.2.20123.133
- Connection Controls Version: 1.2021.1.39
- XrmToolBox Version: 1.2021.1.44
- Tool Version: 1.2020.12.22

**Comment by MscrmTools** [comment]
Hi @readyxrm, In fact, I'm using the quick search view definition to display information about retrieved records. So, I guess you just have to update the view to display the associated language on your source environment to see that information in Portal Records Mover.
This way, I don't have to manage each records view layout
Does it answer your need?

**Comment by readyxrm** [comment]
Thanks, makes total sense!  Cheers!
