### ISSUE TITLE
Suggestion - Do Not Overwrite Site Settings Option

### ISSUE THREAD

**Issue by jtoniolo** [MscrmTools/MscrmTools.PortalRecordsMover#47]
Site Settings are a little different from most of the portal records. These records are sometimes environment specific, particularly when integrating with 3rd party APIs, etc... Because of this, it may not be desirable to overwrite these records if they already exist. This has been a common issue for us while we are actively developing.

The "Get records modified on or after" option does mitigate the issue some/most of the time.

Adding option checkbox for "Do not overwrite site settings" and treating that one record type accordingly would alleviate the issues entirely though.

If you like the idea but don't have the time, I volunteer to do the work.

**Comment by MscrmTools** [comment]
Do I understand correctly if there should be an option to not update site settings but just create new ones?

**Comment by jtoniolo** [comment]
Yes, that is my suggestion.

**Comment by MscrmTools** [comment]
Added in the latest version to be soon released

**Comment by MBSteve** [comment]
@MscrmTools Looks like this setting is dictating imports for all entities, rather than just the adx_sitesetting entity.
