### ISSUE TITLE
New "CreateOnlyNewSiteSettings" setting is triggering on all entities rather than only on site settings

### ISSUE THREAD

**Issue by MBSteve** [MscrmTools/MscrmTools.PortalRecordsMover#48]
RecordManager.cs: line 171 is currently:

`if (settings.CreateOnlyNewSiteSettings)`

should be

`if (settings.CreateOnlyNewSiteSettings && record.LogicalName == "adx_sitesetting)`

**Comment by MscrmTools** [comment]
Thank you for reporting. I'm fixing it ASAP
