### ISSUE TITLE
Unable to Transfer Advanced Form Metadata Records

### ISSUE THREAD

**Issue by DaveStabilify** [MscrmTools/MscrmTools.PortalRecordsMover#50]
It looks like schema names may have changed because when I try to transfer Advanced Form Metadata records, the follow error is logged:

Error	sta_submittedbycontact (Advanced Form Metadata/567fb31a-18cd-eb11-bacc-00224806d538): 'adx_webformmetadata' entity doesn't contain attribute with Name = 'adx_entityformforcreateinwebformmetadata' and NameMapping = 'Logical'.

**Comment by MscrmTools** [comment]
I guess the exact cause is that you have a newer version on source environment than target environment and there are some missing attributes in target.
Can you check that?

**Comment by rmuhammed** [comment]
Yes it is different version. In dev Dynamics 365 Portals - Portal base is 9.3 and it is 9.2 in QA.
I am not sure how to upgrade it. Upgrade button is disabled in QA
![image](https://user-images.githubusercontent.com/18535928/221828144-1f828b05-f5d0-41a7-b177-072baaa2cd5b.png)

**Comment by MscrmTools** [comment]
In PPAC, under Power Pages portal menu, you can search for updates
![image](https://user-images.githubusercontent.com/10774317/221858674-25e07b10-b84a-458d-b463-c5635a06cc22.png)
