### ISSUE TITLE
Exporting / importing creates duplicate records

### ISSUE THREAD

**Issue by jonianas** [MscrmTools/MscrmTools.PortalRecordsMover#51]
Hi, this is more of a query than a bug. I'm trying to export a portal, and im getting duplicate records (for example, 2 root page records for home, one with the default template and one with the correct template) during import. I've validated in portal management that the source website only has 1 root during export. Is it possible to track where the duplicate is coming from? I'm new with d365 as well, so apologies in advance. Thank you.

**Comment by MscrmTools** [comment]
Maybe the root cause of this is there is always an existing website with its pages in a target env.
So exporting from source and importing to target does not remove existing pages.
You should maybe clean the target website before or after the import

**Comment by jonianas** [comment]
Thanks, that makes sense, we'll try this out and i'll give an update. Btw, I found this weird because we were using the tool a few months ago without any issues.

**Comment by MscrmTools** [comment]
@jonianas, is this still an issue?

**Comment by jonianas** [comment]
Hi, I wasnt able to retest using the same XML, but newer XML backups seem to work okay. Ill close the issue for now, and deepest apologies for the very late update.
