### ISSUE TITLE
Error while retrieving records

### ISSUE THREAD

**Issue by rmuhammed** [MscrmTools/MscrmTools.PortalRecordsMover#54]
I selected all entities in the list and tried to to retrieve records. I see the error below

`See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.InvalidCastException: Unable to cast object of type 'Microsoft.Xrm.Sdk.EntityCollection' to type 'Microsoft.Xrm.Sdk.EntityReference'.
   at Microsoft.Xrm.Sdk.Entity.GetAttributeValue[T](String attributeLogicalName)
   at MscrmTools.PortalRecordsMover.Controls.RecordsListerControl.GetRecordValue(Entity record, String value, EntityMetadata emd)
   at MscrmTools.PortalRecordsMover.Controls.RecordsListerControl..ctor(List`1 records, EntityMetadata emd, String layoutXml)
   at MscrmTools.PortalRecordsMover.MyPluginControl.<tsbRetrieveRecords_Click>b__34_1(RunWorkerCompletedEventArgs evt)
   at XrmToolBox.Extensibility.Worker.<>c__DisplayClass4_0.<WorkAsync>b__0(Object s, RunWorkerCompletedEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnRunWorkerCompleted(RunWorkerCompletedEventArgs e)

**Comment by MscrmTools** [comment]
I do not reproduce.
Can you tell me what is your version of Power Apps Portal?

**Comment by rmuhammed** [comment]
Portal version : 9.4.3.40
Thanks
Muhammed Rafiq
Engineer III
Office
Wipfli LLP / Tower B, 4th Floor, Global Village Tech Park, Mylasandra / Pattenegere Villages, RVCE Post, Off Mysore road, Bangaluru, IND 560059
wipfli.com<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.wipfli.com%2F&data=04%7C01%7CMRafiq%40wipfli.com%7C534223416ae1438ce90708d9e26ade27%7Cfea858f0512d46498228d78fd9ef3c7e%7C0%7C0%7C637789770891850848%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=gbUbIvczDnTQ0tD4SgT5QyWOzKqkACosOki5BMt2bpA%3D&reserved=0> / Facebook<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.facebook.com%2FWipfliLLP&data=04%7C01%7CMRafiq%40wipfli.com%7C534223416ae1438ce90708d9e26ade27%7Cfea858f0512d46498228d78fd9ef3c7e%7C0%7C0%7C637789770891850848%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=qundxWtJRMCJEiEZj8ESCCEda2M%2BMsd8Cyq2En38HcQ%3D&reserved=0> / Twitter<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.twitter.com%2FWipfli_LLP&data=04%7C01%7CMRafiq%40wipfli.com%7C534223416ae1438ce90708d9e26ade27%7Cfea858f0512d46498228d78fd9ef3c7e%7C0%7C0%7C637789770891850848%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=cv9wJGtrKXSdORyJoBXYNPlTpDJN4sD%2BYDF8t4s0H%2B4%3D&reserved=0>


Member of Allinial Global, an association of legally independent firms

***@***.***

**Comment by rmuhammed** [comment]
I found the error is coming when I select "Portal Comment" entity

**Comment by MscrmTools** [comment]
New version is available
