### ISSUE TITLE
Suggestion: make functions available via an API

### ISSUE THREAD

**Issue by polshgiant** [MscrmTools/MscrmTools.PortalRecordsMover#57]
It would be amazing if I could run the tool from the command line to export my data and then push it to an org.

**Comment by MscrmTools** [comment]
@polshgiant You can do this with the [PowerApps CLI](https://learn.microsoft.com/en-us/power-apps/maker/portals/power-apps-cli) now

Also, I think @jamesnovak had a [console version](https://github.com/jamesnovak/PortalRecordsMoverConsolepwoerapps ) of this tool but couldn't tell if it's still maintained
