### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by generallouay** [MscrmTools/MscrmTools.PortalRecordsMover#60]
Hi,
I've been suffering from this error message for 3 hours.
It occurs every time I try to export/import a record from any environment.
After investigating for a while I found out there's something wrong with the last release.
Downloaded a 2019 version of the tool and it worked perfectly.
I hope you fix the new version ASAP.
thank you for your time.

![image](https://user-images.githubusercontent.com/91007888/199031269-f3f07ca9-cb82-4b0e-ad11-59570dd32800.png)

**Comment by MscrmTools** [comment]
Is it possible to get the details of the error?
It would greatly help to understand where the error occurs

**Comment by generallouay** [comment]
> Is it possible to get the details of the error? It would greatly help to understand where the error occurs 


>
for sure.
I included a file with the full error details.
Again the error occurs every time I click Import/Export or even transfer.
Update : the version I mentioned previously did not work properly.
It did Export/Import but with no results.
[record_mover_issue.txt](https://github.com/MscrmTools/MscrmTools.PortalRecordsMover/files/9902540/record_mover_issue.txt)

**Comment by melindastewart** [comment]
I'm seeing exactly the same error since the last update as well. I can't do any transfers or import/exports with this version.

Not sure if it's related, but I'm seeing the following error in the XrmToolBox log every time this occurs. 
```
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Error	2	3/11/2022 8:09:04 PM  Failed to find Short Name for Oceania
Source	: Microsoft.Xrm.Tooling.Connector
Method	: GetServerShortNameByDisplayName
Date	: 3/11/2022
Time	: 8:09:04 PM
Error	: Object reference not set to an instance of an object.
Stack Trace	: at Microsoft.Xrm.Tooling.Connector.Model.CrmOnlineDiscoveryServers.GetServerShortNameByDisplayName(String serverDisplayName, Boolean isO365)
```

Is there any way to go back to the last version of the tool?

**Comment by generallouay** [comment]
> Is there any way to go back to the last version of the tool? 

Yes there is.
The senior in my team somehow found a backup of the previous XRMToolBox on his machine.
You can [download](https://www.mediafire.com/file/acnwx4578mo0798/Backup_20221102-092130.zip/file) then unzip the file and launch the app from the extracted folder itself.

**Comment by MscrmTools** [comment]
You can also download and extract the version you want from Nuget: https://www.nuget.org/packages/MscrmTools.PortalRecordsMover#versions-body-tab

Then change the extension nupkg to zip, extract, go to lib/net45/Plugins and you will find the file you need to copy in your Plugins directory.

I will try to review/fix the issue tomorrow if I find time to do so

Thank you for your patience

**Comment by MscrmTools** [comment]
Hum... not sure the issue is with the tool but maybe with XrmToolBox itself. I found an issue with latest version of XrmToolBox and even old version of Portal Records Mover should be impacted.

**Comment by MscrmTools** [comment]
Ok, so I can confirm the issue is with XrmToolBox itself.

I need to provide a fix ASAP

**Comment by MscrmTools** [comment]
Issue fixed! Please download latest version of XrmToolBox => 1.2022.11.59
