### ISSUE TITLE
I can't move webfiles due to error with business unit id error

### ISSUE THREAD

**Issue by baraveze** [MscrmTools/MscrmTools.PortalRecordsMover#66]
I tried to move power pages portal from dev environment to test environment and I get this error: "Entity 'businessunit' With Id = 745e195c-eae0-ec11-bb3d-000d3a8ea0b5 Does Not Exist".

First, I don't have the chance to map in anyway that information from source to target. Then it's expected that GUID between different environments don't be the same. Isn't the tool searching parent records by name?. For example, Business units have the same exactly name between dev and test.

I have the same issue with lot of other entities as well.

Any help on this? Thanks!

**Comment by MscrmTools** [comment]
Hi, I need to check for this in code but I don't have so much time these days...

**Comment by MscrmTools** [comment]
@baraveze I will simply avoid to export lookups that points to businessunit or systemuser tables. That should fixed the issue
