### ISSUE TITLE
[Feature Request] Get Records Created/Modified Before Date

### ISSUE THREAD

**Issue by Setnour6** [MscrmTools/MscrmTools.PortalRecordsMover#67]
Currently, you can only get records created on or after a specified date, but not before. This proposal involves adding two new date pickers besides the existing two date pickers that gathers records before a date instead of after.

This is useful for when you want to look back at all specific points of created and modified records without also needing to see the recently changed/modified records. 

The biggest issues with making the proposal happen is that the only condition operators are `OnOrAfter` or `OnOrBefore`, so the date calculation still has to reference the exact date. I attempted a small workaround with `AddDays(-1)` (this isn't something I usually work with and not to mention that I am new with XrmToolBox plugin development, bear with me) but I wasn't able to properly test it due to the appearance of the new date pickers overriding and shoving the existing date pickers rather than appearing on the right.

**Comment by Setnour6** [comment]
I just tried it now. I was originally thinking that it could look like the two new date pickers were to the right of the original datepickers, something like this: 
![image](https://github.com/MscrmTools/MscrmTools.PortalRecordsMover/assets/70764728/1be0a3ac-3c45-4790-a8e8-dbcd14490960)
_Note that I used photo editing for the image above._
The existing implementation is good too, so you can keep it the way you implemented it if you want.

I also found that when I select the "created on or before" and the "modified on or before" checkboxes, it gets the records beyond the specified date (i.e. modified on 2023 instead of 2022).

One more thing: given the current logic of finding records, is it also possible for you to make two more checkboxes that gets created/modified records around a specific date range? I thought I could do it with the checkboxes after the update but the expectations there went differently.
![image](https://github.com/MscrmTools/MscrmTools.PortalRecordsMover/assets/70764728/3a84d8a1-b1f9-4d3a-961e-bdb9d2e97519)
_Note that I used photo editing for the image above._
Alternatively, you can make a checkbox for when you want the date range to be calculated or not.

**Comment by mdobriant** [comment]
After upgrading to the latest version I'm getting an error tied to these new filters when loading settings from an xml file. I tried adding CreateFilterBefore and ModifyFilterBefore tags to the xml but no luck. Any ideas?

![image](https://github.com/MscrmTools/MscrmTools.PortalRecordsMover/assets/102323927/ad57f831-eefa-4006-a776-70471997858c)

![image](https://github.com/MscrmTools/MscrmTools.PortalRecordsMover/assets/102323927/803f9414-fcfa-47d0-b1d5-acfc863adcd1)

**Comment by MscrmTools** [comment]
Fixing it right now
