### ISSUE TITLE
Only include notes that related to web files

### ISSUE THREAD

**Issue by squiso** [MscrmTools/MscrmTools.PortalRecordsMover#9]
Hi,

Wonderful work on the add-on. Just a quick idea.. I'm currently migrating a clients portal configuration which includes web files / notes. It would be handy if the notes filtered down to only note related to web files. This would save having to deselect all notes and manually verify / select appropriate notes. It be controlled by a new option.

**Comment by readyxrm** [comment]
If you exclude "note" (uncheck it) but keep webfiles, the process will copy the note/attachments linked to the webfile records.  I have found for CSS files and images, even after a cache refresh they don't always show up right away, so it may seem like they did not copy (but they did).  Hope that helps.

**Comment by MscrmTools** [comment]
Thanks for the help @readyxrm
